export default {
  FETCH_USER_INFO_START: 'FETCH_USER_INFO_START',
  FETCH_USER_INFO_SUCCESS: 'FETCH_USER_INFO_SUCCESS',
  FETCH_USER_INFO_FAILURE: 'FETCH_USER_INFO_FAILURE',
  SAVE_USER_INFO_TO_STORE: 'SAVE_USER_INFO_TO_STORE',
}