export default {
  GET_GROUP_POSTS_START: 'GET_GROUP_POSTS_START',
  GET_GROUP_POSTS_SUCCESS: 'GET_GROUP_POSTS_SUCCESS',
  GET_GROUP_POSTS_FAILURE: 'GET_GROUP_POSTS_FAILURE',
  SAVE_GROUP_POSTS_TO_STORE: 'SAVE_GROUP_POSTS_TO_STORE',
  ADD_POST: 'ADD_POST',
  ADD_POST_START: 'ADD_POST_START',
  ADD_POST_FAILURE: 'ADD_POST_FAILURE',
}