export default {
  GET_GROUP_POSTS_START: 'GET_GROUP_POSTS_START',
  GET_GROUP_POSTS_SUCCESS: 'GET_GROUP_POSTS_SUCCESS',
  GET_GROUP_POSTS_FAILURE: 'GET_GROUP_POSTS_FAILURE',
  SAVE_GROUP_POSTS_TO_STORE: 'SAVE_GROUP_POSTS_TO_STORE',
}